apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.datadog.name }}
rules:
- apiGroups: [""]
  resources:
    - services
    - events
    - endpoints
    - pods
    - nodes
    - componentstatuses
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["nodes/proxy", "nodes/metrics", "nodes/spec"]
  verbs: ["get"]
- nonResourceURLs: ["/version", "/healthz"]
  verbs: ["get"]
