apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.datadog.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.datadog.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.datadog.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.datadog.name }}
    spec:
      containers:
      - name: {{ .Values.datadog.name }}
        image: gcr.io/datadoghq/agent:latest
        env:
          - name: DD_API_KEY
            valueFrom:
              secretKeyRef:
                name: datadog-secret
                key: api-key
          - name: DD_SITE
            value: "datadoghq.com"
        resources:
          limits:
            memory: 512Mi
            cpu: 500m
        volumeMounts:
            mountPath: /host/proc
            readOnly: true
      volumes:
        - name: proc
          hostPath:
            path: /proc