{{- range $repo_key, $repo_value := .Values.repositoryCredentials }}
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo-{{ $repo_key }}
  namespace: {{ $.Release.Namespace }}
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
data:
  url: {{ $repo_value.url | b64enc }}
  username: "{{ $repo_value.username }}"
  password: "{{ $repo_value.password }}"
{{- end }}